DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID INT PRIMARY KEY, NAME VARCHAR(255), AUTHORID INT, GENREID INT);