DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID bigint(20) NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID bigint(20) NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  AUTHORID INT,
  GENREID INT,
  PRIMARY KEY (ID),
  CONSTRAINT fk_author
    FOREIGN KEY (AUTHORID)
    REFERENCES AUTHOR (ID)
    ON DELETE CASCADE,
  CONSTRAINT fk_genre
    FOREIGN KEY (GENREID)
    REFERENCES GENRE (ID)
    ON DELETE CASCADE
);