spring:
  data:
    mongodb:
      database: 777_books
      host: localhost
      customseq: customSequences
      port: 27017
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["restart"]