spring:
  data:
    mongodb:
      database: 777_books
      host: localhost
      customseq: customSequences
      port: 27017
      url: http://localhost:9090
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "[*]"
logging:
  path: /
  file: log.txt
