version: '3'
services:
  main:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    depends_on:
      - db
  db:
    image: "mongo:3.4.20-xenial"
    ports:
      - "27017:27017"