apiVersion: extensions/v1beta1
#apiVersion: v1
#kind: Pod
kind: Deployment
metadata:
  name: two-containers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: spring17-minikube
          image: spring17:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: "27017"
          ports:
            - containerPort: 8080
        - name: mongodb-minikube
          image: mongo:3.4.20-xenial
          ports:
            - containerPort: 27017